language: node_js
node_js:
- '5'
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
before_deploy:
- npm run build
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  api_key:
    secure: u+d9OC18vN64M2fpHks3rnDCTPtUlSVmZlOLpDFzsgaPB5khoNCiQkWD8prNCJuW0ne8nrhaSLR98t0WhQKc0pkbRT9N+PjToi+7Mg+qaRAJCS/pK8+jm93OtiTXxmmdsr8/dqbhezrAUlxRDMvFw+5F2ZbZuKtL4VUxkoGMFeTw387cNTtaBzXYRbe0dMKSFtAJ8lL8N0PA7tbz/clt7yXRtE7Tx75FYtNDNtv+c4Oap/DgLn2/97msIVdDxtbyV4l0Mbq3Pia5o01RYl5T2gqplu6YUW85VI/rLtF6U8IXL8gg2n80GtOf7Sp8TXFyUM2StWcX/qIJQdmKt0r2QVvalj8DGU269fTRprKqQt5tCEiI2mSujPHTBBQE8IdhJ35fuG51o2fjNsNtcPvTVMPf4Og5VKnwEuU7SnBDvzThJ/tfv+nZFNTbTXbsDIoWwFZghA7wDYIIOHQ/NXIYQ/tXoO/OUmqG2NafLI6whP+bAUkbMHz66PTgqabbfTb4uzXd/e97BuIWptleOOdajEUVBWI3V5fkpI0baLh6En597nWFJpkUrFxfnewtlkE6OXN3MjnDku32/QiZsoJOkALC5YsBgYpl6Ux1OTJI5yAdBvQF9WpT9A+5eoFwTDTDErKoFFKqiWo9d4HYOInFBGLZXcZRrw0jLYay2BCSW8s=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - "/^v[0-9]/"
